services:
    main_brainz:
        image: gtdonny18/main_brainz:latest
        container_name: main_brainz_container
        tty: true
    
        restart: "always"

#        user: '1000:1000'

        environment:
            - DISPLAY::0

        devices:
            - /dev/video0:/dev/video0
            - /dev/video1:/dev/video1
            
        volumes:
            - ./hand_control:/root/hand_control
            
        working_dir: /root/hand_control

        
        
networks:
    that_network:
        ipam:
            driver: default
            config:
                - subnet: "192.168.20.0/24"
